[package]
name = "xgrep"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.23", features = ["derive"] }
crossbeam = "0.8.2"
crossbeam-channel = "0.5.8"
crossbeam-queue = "0.3.8"
crossbeam-utils = "0.8.16"
rand = "0.8.5"
regex = "1.9.3"
walkdir = "2.3.3"
